cleanup feedback
Conflicts:
	contrib/core/actions/send_mail/send_mail

diff --git a/contrib/core/actions/send_mail/send_mail b/contrib/core/actions/send_mail/send_mail
--- a/contrib/core/actions/send_mail/send_mail
+++ b/contrib/core/actions/send_mail/send_mail
@@ -3,6 +3,13 @@
 HOSTNAME=$(hostname -f)
 FROM="stanley@${HOSTNAME}"
 SENDMAIL=`which sendmail`
+LINE_BREAK=""
+
+if [ $? -ne 0 ]; then
+    echo "Unable to find sendmail binary in PATH" >&2
+    exit 2
+fi
+
 MAIL="$SENDMAIL -t"
 FOOTER="This message was generated by Stanley Action `basename $0` running on `hostname`"
 TO=$1
@@ -15,6 +22,12 @@ CONTENT_TYPE=$1
 shift
 BODY="$@"
 
+if [[ "${CONTENT_TYPE}" = "text/html" ]]; then
+  LINE_BREAK="<br><br>"
+else
+  LINE_BREAK="\n\n"
+fi
+
 if [[ -z "${BODY// }" && $SEND_EMPTY_BODY == 'True' ]] || [[ -n $BODY ]]; then
   ${MAIL} <<EOF
 TO: ${TO}
@@ -23,7 +36,7 @@ SUBJECT: ${SUBJECT}
 Content-Type: ${CONTENT_TYPE}
 
 ${BODY}
-<br><br>
+${LINE_BREAK}
 ${FOOTER}
 
 EOF
