Add some unit / integration tests for sendmail action.

diff --git a/contrib/core/actions/send_mail/send_mail b/contrib/core/actions/send_mail/send_mail
--- a/contrib/core/actions/send_mail/send_mail
+++ b/contrib/core/actions/send_mail/send_mail
@@ -3,14 +3,27 @@
 HOSTNAME=$(hostname -f)
 LINE_BREAK=""
 
-SENDMAIL=`which sendmail`
-if [ $? -ne 0 ]; then
-    echo "Unable to find sendmail binary in PATH" >&2
-    exit 2
-fi
-
-MAIL="$SENDMAIL -t"
 FOOTER="This message was generated by StackStorm action `basename $0` running on `hostname`"
+
+# Allow user to provide a custom sendmail binary for more flexibility and easier
+# testing
+SENDMAIL_BINARY=$1
+
+if [ "${SENDMAIL_BINARY}" = "None" ]; then
+    # If path to the sendmail binary is not provided, try to find one in $PATH
+    SENDMAIL=`which sendmail`
+
+    if [ $? -ne 0 ]; then
+        echo "Unable to find sendmail binary in PATH" >&2
+        exit 2
+    fi
+
+    MAIL="$SENDMAIL -t"
+else
+    MAIL="${SENDMAIL_BINARY}"
+fi
+shift
+
 if [[ $1 =~ '@' ]]; then
   FROM=$1
 else
