debian maintainer scripts update, reown packs/virtualenvs on upgrade (if required)
Cherry-picked from StackStorm/st2-packages@a441bd71606421b01b6516a8fa587feb460b11c1

diff --git a/packages/st2/debian/postinst b/packages/st2/debian/postinst
--- a/packages/st2/debian/postinst
+++ b/packages/st2/debian/postinst
@@ -4,24 +4,58 @@
 # see: dh_installdeb(1)
 
 set -e
-ST2_USER=st2
-SYS_USER=stanley
 
-PERMS=$(cat <<EHD
-/etc/st2/htpasswd             ${ST2_USER}:${ST2_USER} 600
-/opt/stackstorm/exports       ${ST2_USER}:${ST2_USER} 755
-/opt/stackstorm/packs         ${SYS_USER}:${ST2_USER} 775
-/opt/stackstorm/virtualenvs   ${SYS_USER}:${ST2_USER} 775
-/var/log/st2                  ${ST2_USER}:${ST2_USER} 775
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+SYS_USER=stanley
+ST2_USER=st2
+ST2_UPGRADESTAMP="/tmp/.stamp-stackstorm-st2-deb-package"
+upgrading=0
+
+## Permissions of files which should be set on install
+DEST_PERMS=$(cat <<EHD | sed 's/\s\+/ /g'
+ug+rw _sysuser:_st2user /opt/stackstorm/packs
+ug+rw _sysuser:_st2user /opt/stackstorm/virtualenvs
+ug+rw _st2user:_st2user /var/log/st2
+755 _st2user:root       /opt/stackstorm/exports
+600 _st2user:_st2user   /etc/st2/htpasswd
 EHD
 )
 
-echo "$PERMS" | while read line; do
-  path=`echo $line | cut -f1 -d' '`
-  creds=`echo $line | cut -f2 -d' '`
-  mode=`echo $line | cut -f3 -d' '`
-  chown -f $creds $path && chmod -f $mode $path
-done
+## Fix directories permissions on install (different across maint scripts!)
+set_permissions() {
+  local fileperms="$1"
+  fileperms=$(echo "$fileperms" | sed -e "s/_sysuser/$SYS_USER/g" -e "s/_st2user/$ST2_USER/g")
+  # Reqursively chown given destinations!
+  echo "$fileperms" | cut -f2,3 -d' ' | xargs -n2 chown -R
+  # Set directories mode
+  echo "$fileperms" | cut -f1,3 -d' ' | xargs -n2 chmod -R
+}
+
+case "$1" in
+    configure)
+      # Initially set destination files owenership (only on the first install)
+      [ -f $ST2_UPGRADESTAMP ] && upgrading=1 && rm $ST2_UPGRADESTAMP || :
+      [ "$upgrading" = 0 ] && set_permissions "$DEST_PERMS" || :
+    ;;
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
diff --git a/packages/st2/debian/postrm b/packages/st2/debian/postrm
--- a/packages/st2/debian/postrm
+++ b/packages/st2/debian/postrm
@@ -5,17 +5,39 @@
 
 set -e
 
-if [ "$1" = "remove" ]; then
-  [ -f /etc/logrotate.d/st2 ] && mv -f /etc/logrotate.d/st2 /etc/logrotate.d/st2.disabled
-fi
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-if [ "$1" = "purge" -o "$1" = "dissappear" ]; then
-  [ -f /etc/logrotate.d/st2.disabled ] && rm -f /etc/logrotate.d/st2.disabled
-fi
+## Save st2 logrotate config on remove, but wipe it out on purge.
+preserve_logrotate() {
+  if [ "$1" = remove ]; then
+    [ -f /etc/logrotate.d/st2 ] && mv /etc/logrotate.d/st2-pkgsaved.disabled 1>/dev/null 2>&1 || :
+  elif [ "$1" = purge ]; then
+    rm -f /etc/logrotate.d/st2-pkgsaved.disabled 1>/dev/null 2>&1 || :
+  fi
+}
 
-# case "$1" in
-#     purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
-#     ;;
+case "$1" in
+    remove|purge)
+      preserve_logrotate "$1"
+    ;;
+    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+    ;;
+    *)
+        echo "postrm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
