Added fixtures and asserts pack installs.  Made wolf ascii art conditional on success, fixed action list width

diff --git a/tools/st2-self-check b/tools/st2-self-check
--- a/tools/st2-self-check
+++ b/tools/st2-self-check
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 ## Script to install samples, tests, and run all workflows in tests pack.
-
+ERRORS=0
 PACKS="tests examples"
 
 #Determine Distro
@@ -18,11 +18,20 @@ else
   exit 2
 fi
 
+# Install test prerequisites
+${PYTHONPACK}/st2common/bin/st2-setup-tests asserts
+${PYTHONPACK}/st2common/bin/st2-setup-tests fixtures
+
 # Install required packs if necessary
 for PACK in $PACKS; do
   CHECK=`st2 action list --pack=${PACK} | grep ${PACK}`
   if [ $? -ne 0 ]; then
-    INSTALL=`${PYTHONPACK}/st2common/bin/st2-setup-${PACK}`
+    if [ "$PACK" == "tests" ]; then
+      ARG="tests"
+    else
+      ARG="" 
+    fi
+    INSTALL=`${PYTHONPACK}/st2common/bin/st2-setup-${PACK} ${ARG}`
 
     EXITCODE=$?
     echo $INSTALL
@@ -30,7 +39,7 @@ for PACK in $PACKS; do
 done
 
 # Retrieve test action list
-TEST_ACTION_LIST=`st2 action list --pack=tests -w 30 | awk '{ print $2 }' | grep -v "|" | grep -v "ref"`
+TEST_ACTION_LIST=`st2 action list --pack=tests -w 90 | awk '{ print $2 }' | grep -v "|" | grep -v "ref"`
 
 # Run all the tests
 for TEST in $TEST_ACTION_LIST
@@ -45,15 +54,16 @@ for TEST in $TEST_ACTION_LIST
         else
             echo "OK!"
         fi
+        ERRORS=$(($ERRORS + $?))
     done
 
 echo -n "Attempting Example examples.mistral_examples..."
 MISTRAL_EXAMPLES=`st2 run examples.mistral_examples -j`
 CHECK_STATUS=`echo ${MISTRAL_EXAMPLES} | grep '"status": "succeeded"'`
-if [ $? -ne 0 ]; then
-    echo -e "ERROR!"
-    #echo -e "ERROR!\nOUTPUT: ${MISTRAL_EXAMPLES}"
-    #exit 2
+if [ $ERRORS -ne 0 ]; then
+    echo "ERROR!"
+    echo "Tests failed.  See above.  Also check the execution list for details."
+    echo "st2 execution list"
 else
     echo -e "OK!"
 
