Fix examples.mistral_examples in st2-self-check script

diff --git a/tools/st2-self-check b/tools/st2-self-check
--- a/tools/st2-self-check
+++ b/tools/st2-self-check
@@ -94,7 +94,6 @@ done
 
 # Retrieve test action list
 TEST_ACTION_LIST=`st2 action list --pack=tests -w 90 | awk '{ print $2 }' | grep -v "|" | grep -v "ref"`
-TEST_ACTION_LIST+=' examples.mistral_examples'
 
 # Run all the tests
 for TEST in $TEST_ACTION_LIST
@@ -116,6 +115,16 @@ do
         echo "OK!"
     fi
 done
+
+echo -n "Attempting Example examples.mistral_examples..."
+MISTRAL_EXAMPLES=`st2 run examples.mistral_examples -j`
+CHECK_STATUS=`echo ${MISTRAL_EXAMPLES} | grep '"status": "failed"'`
+if [ $? -ne 1 ]; then
+    echo -e "ERROR!"
+    ((ERRORS++))
+else
+    echo "OK!"
+fi
 
 if [ $ERRORS -ne 0 ]; then
     echo "SELF CHECK FAILED!"
